test(parser): fix test failure introduced by adding >= operator
The test failed with:
Error:      	An error is expected but got nil.
Test:       	TestParseExpressions/foo{a>="b"}

The original author of the test had arbitrarily chosen >= as an invalid
token; us introducing >= as a valid operator consequently broke that
test.